name: CI

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    name: 部署
    runs-on: [ubuntu-latest, x64, small]
    concurrency:
      enable: true
      max: 1
      exceed-action: IGNORE
    steps:
      - name: Run deploy
      	run: echo "deploy"
